## ASSESMENT WITH QUESTIONS:
1.understand logistic regression algorithm 
2.apply descriptive stats to summarise data
3.perform data cleaning and preprocessing 
4.apply feature scaling and encoding technique 
5.build and evaluate a logistic regression model

## DESCRIPTIVE STATISTICS

In [2]:
import pandas as pd

df = pd.read_excel("new_data.xlsx")

# First look
print(df.head())

     X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [3]:
# Structure
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      768 non-null    float64
 1   X2      768 non-null    float64
 2   X3      768 non-null    float64
 3   X4      768 non-null    float64
 4   X5      768 non-null    float64
 5   X6      768 non-null    int64
 6   X7      768 non-null    float64
 7   X8      768 non-null    int64
 8   Y1      768 non-null    float64
 9   Y2      768 non-null    float64
dtypes: float64(8), int64(2)
memory usage: 60.1 KB
None

In [4]:
# Statistical summary
print(df.describe())

               X1          X2          X3          X4         X5          X6  \
count  768.000000  768.000000  768.000000  768.000000  768.00000  768.000000
mean     0.764167  671.708333  318.500000  176.604167    5.25000    3.500000
std      0.105777   88.086116   43.626481   45.165950    1.75114    1.118763
min      0.620000  514.500000  245.000000  110.250000    3.50000    2.000000
25%      0.682500  606.375000  294.000000  140.875000    3.50000    2.750000
50%      0.750000  673.750000  318.500000  183.750000    5.25000    3.500000
75%      0.830000  741.125000  343.000000  220.500000    7.00000    4.250000
max      0.980000  808.500000  416.500000  220.500000    7.00000    5.000000

               X7         X8          Y1          Y2
count  768.000000  768.00000  768.000000  768.000000
mean     0.234375    2.81250   22.307195   24.587760
std      0.133221    1.55096   10.090204    9.513306
min      0.000000    0.00000    6.010000   10.900000
25%      0.100000    1.75000   12.992500   15.620000
50%      0.250000    3.00000   18.950000   22.080000
75%      0.400000    4.00000   31.667500   33.132500
max      0.400000    5.00000   43.100000   48.030000

Features: X1–X8
Targets available: Y1 and Y2 (both continuous)

Since logistic regression is for classification, we’ll first convert one target into a binary class.

## Logistic Regression

we create a Target for Logistic Regression

We convert Y1 into two classes:

1 = High energy building (above median)

0 = Low energy building (below median)

In [5]:
# Create binary target from Y1
df['Target'] = (df['Y1'] > df['Y1'].median()).astype(int)

print(df['Target'].value_counts())

Target
0    384
1    384
Name: count, dtype: int64

In [6]:
##Data Cleaning: this datset is already clean
print(df.isnull().sum())

X1        0
X2        0
X3        0
X4        0
X5        0
X6        0
X7        0
X8        0
Y1        0
Y2        0
Target    0
dtype: int64

In [7]:
print(df.duplicated().sum())

0

In [ ]:
## Feature Selection
X = df[['X1','X2','X3','X4','X5','X6','X7','X8']] ##independent variables
y = df['Target'] ## target variable

In [10]:
##Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [11]:
##Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [12]:
## Logistic Regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [13]:
### Convert categorical columns to category type
df['X6'] = df['X6'].astype('category')
df['X8'] = df['X8'].astype('category')

# One-hot encoding
df = pd.get_dummies(df, columns=['X6','X8'], drop_first=True)

print(df.head())

     X1     X2     X3      X4   X5   X7     Y1     Y2  Target   X6_3   X6_4  \
0  0.98  514.5  294.0  110.25  7.0  0.0  15.55  21.33       0  False  False
1  0.98  514.5  294.0  110.25  7.0  0.0  15.55  21.33       0   True  False
2  0.98  514.5  294.0  110.25  7.0  0.0  15.55  21.33       0  False   True
3  0.98  514.5  294.0  110.25  7.0  0.0  15.55  21.33       0  False  False
4  0.90  563.5  318.5  122.50  7.0  0.0  20.84  28.28       1  False  False

    X6_5   X8_1   X8_2   X8_3   X8_4   X8_5
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False  False  False  False  False
3   True  False  False  False  False  False
4  False  False  False  False  False  False

In [14]:
## model evaluation
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))

Accuracy: 0.9805194805194806
Confusion Matrix:
 [[70  1]
 [ 2 81]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98        71
           1       0.99      0.98      0.98        83

    accuracy                           0.98       154
   macro avg       0.98      0.98      0.98       154
weighted avg       0.98      0.98      0.98       154

ROC-AUC Score: 0.9971152214491771

## USA HOUSING DATASET

In [18]:
import pandas as pd

df = pd.read_csv("USA_Housing.csv")
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object
dtypes: float64(6), object(1)
memory usage: 273.6+ KB

In [20]:
df.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562388,5.322283,6.299250,3.140000,29403.928702,9.975771e+05
50%,68804.286404,5.970429,7.002902,4.050000,36199.406689,1.232669e+06
75%,75783.338666,6.650808,7.665871,4.490000,42861.290769,1.471210e+06
max,107701.748378,9.519088,10.759588,6.500000,69621.713378,2.469066e+06

In [21]:
## data cleaning
print(df.isnull().sum())

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [22]:
print(df.duplicated().sum())

0

In [23]:
df = df.drop(columns=['Address'])  # Address is text, not useful

In [24]:
## descriptive statistics
df.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562388,5.322283,6.299250,3.140000,29403.928702,9.975771e+05
50%,68804.286404,5.970429,7.002902,4.050000,36199.406689,1.232669e+06
75%,75783.338666,6.650808,7.665871,4.490000,42861.290769,1.471210e+06
max,107701.748378,9.519088,10.759588,6.500000,69621.713378,2.469066e+06

This dataset has no categorical columns, so:

✅ No label encoding
✅ No one-hot encoding needed

(All columns are already numeric)

We convert price into binary categories:

1 → Expensive House (above median price)

0 → Affordable House (below median price)

In [27]:
df['Price_Class'] = (df['Price'] > df['Price'].median()).astype(int)

print(df[['Price','Price_Class']].head())

          Price  Price_Class
0  1.059034e+06            0
1  1.505891e+06            1
2  1.058988e+06            0
3  1.260617e+06            1
4  6.309435e+05            0

In [28]:
X = df.drop(columns=['Price','Price_Class'])
y = df['Price_Class']

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42)

In [31]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))

Accuracy: 0.905
Confusion Matrix:
 [[435  44]
 [ 51 470]]
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.91      0.90       479
           1       0.91      0.90      0.91       521

    accuracy                           0.91      1000
   macro avg       0.90      0.91      0.90      1000
weighted avg       0.91      0.91      0.91      1000

ROC-AUC Score: 0.9704238276319428