## GenAI

Understand the fundamentals of Generative AI and experiment with prompt-based tools.

In [10]:
import pandas as pd

df = pd.read_csv("loan_data.csv")
df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0
1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0
2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0
3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0
4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0

Prompt 1 – Dataset Summary

In [15]:
def genai_tool(prompt, data):
    
    if "summary" in prompt.lower():
        return "This dataset contains loan details such as credit policy, purpose, interest rate, and repayment status."
    
    elif "insight" in prompt.lower():
        return """1. Higher interest rates may increase default chances.
2. Credit policy approval affects loan success.
3. Loan purpose influences repayment behavior."""
    
    elif "feature" in prompt.lower():
        return "Important features include interest rate, income, credit score, and loan purpose."
    
    elif "generate" in prompt.lower():
        return "Loan analysis shows patterns in borrower behavior and financial risk."
    
    else:
        return "Provide a clear prompt."

In [16]:
sample_data = df.head(5).to_string()

print("🔹 Prompt 1: Summary")
print(genai_tool("Give summary of dataset", sample_data))

print("\n🔹 Prompt 2: Insights")
print(genai_tool("Give insights", sample_data))

print("\n🔹 Prompt 3: Feature Analysis")
print(genai_tool("Explain features", sample_data))

print("\n🔹 Prompt 4: Text Generation")
print(genai_tool("Generate analysis", sample_data))

🔹 Prompt 1: Summary
This dataset contains loan details such as credit policy, purpose, interest rate, and repayment status.

🔹 Prompt 2: Insights
1. Higher interest rates may increase default chances.
2. Credit policy approval affects loan success.
3. Loan purpose influences repayment behavior.

🔹 Prompt 3: Feature Analysis
Important features include interest rate, income, credit score, and loan purpose.

🔹 Prompt 4: Text Generation
Loan analysis shows patterns in borrower behavior and financial risk.

In [17]:
def ai_prediction(row):
    if row['int.rate'] > 0.12:
        return "High Risk"
    else:
        return "Low Risk"

df['AI_Risk'] = df.apply(ai_prediction, axis=1)
df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,AI_Risk
0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0,Low Risk
1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0,Low Risk
2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0,High Risk
3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0,Low Risk
4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0,High Risk